# Generated by Django 6.0.5 on 2026-05-22 15:25

import django.db.models.deletion
import tools.generate_nums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tools.generate_nums.generate_uuid7,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100, verbose_name="留言内容")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("is_hidden", models.IntegerField(default=0, verbose_name="是否隐藏")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="留言时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="message.message",
                        verbose_name="留言",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "留言点赞",
                "verbose_name_plural": "留言点赞",
                "db_table": "message_like",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user"), name="unique_message_user_like"
                    )
                ],
            },
        ),
    ]
