# Generated by Django 6.0.5 on 2026-05-17 05:43

import tools.generate_nums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.CharField(
                default=tools.generate_nums.generate_uuid7,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.CharField(
                default=tools.generate_nums.generate_uuid7,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                default=tools.generate_nums.generate_uuid7,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.CharField(
                default=tools.generate_nums.generate_uuid7,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
