# Generated by Django 6.0.5 on 2026-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置键名"
                    ),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "value_type",
                    models.CharField(
                        default="string", max_length=20, verbose_name="值类型"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="配置说明"
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密存储"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_config",
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["key"], name="idx_key")],
            },
        ),
    ]
