# Generated by Django 6.0.5 on 2026-05-17 09:01

import django.db.models.deletion
import tools.generate_nums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tools.generate_nums.generate_uuid7,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("url", models.URLField(max_length=2000, verbose_name="链接")),
                ("image_url", models.URLField(blank=True, verbose_name="图片")),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="十六进制颜色码，如 #ff0000",
                        max_length=7,
                        verbose_name="主题色",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源链接",
                "verbose_name_plural": "资源链接",
                "db_table": "link_link",
                "ordering": ["-created_at"],
            },
        ),
    ]
